default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: meu_portifolio_development


test:
  <<: *default
  database: meu_portifolio_test


production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
